name: Build and Push Docker Image

on:
  push:
    branches:
      - 'main'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 获取 GitHub Actions 的运行编号作为版本号
      - name: Get run number
        id: version
        run: echo "::set-output name=version::${GITHUB_RUN_NUMBER}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          provenance: false
          push: true
          tags: finalpi/clash-auto-change:${{ steps.version.outputs.version }}, finalpi/clash-auto-change:latest
          platforms: linux/amd64,linux/arm64/v8